// Code generated by "stringer -type=blockType"; DO NOT EDIT.

package smgo

import "strconv"

const _blockType_name = "nodeBlockcontainerHeadercontainerFooter"

var _blockType_index = [...]uint8{0, 9, 24, 39}

func (i blockType) String() string {
	if i < 0 || i >= blockType(len(_blockType_index)-1) {
		return "blockType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _blockType_name[_blockType_index[i]:_blockType_index[i+1]]
}
